### ISSUE TITLE
PR #3 merged but not published on npm (v0.4.8)

### ISSUE THREAD

**Issue by jeandat** [wwilsman/redux-deep-diff#4]
Hi Wil, 
You merged PR #3 but never pushed a v0.4.8 to npm. 
So the PR is not on npm. 
Any reason for that?

**Comment by wwilsman** [comment]
Hi Jean! Thanks for the issue!

There is actually no reason other than I never needed the feature and I didn't realize it wasn't released. 😅 

The release process usually happens when I merge PRs that have a version increment. Looks like that PR just never incremented the version number. I just bumped that and fixed the deploy script so a new `0.5.0` version should be released soon. 

Thanks for bringing this to my attention! 😀

**Comment by jeandat** [comment]
Your welcome. Thanks for the release.

Jean
